#!/bin/bash
python_bin=$(which python)
case $python_bin in
	*.virtual*)
		db_file="$HOME/Code/pyrecipe/pyrecipe/db/recipes.db"
		;;
	*)
		db_file="$HOME/.local/share/pyrecipe/recipes.db"
		;;
esac

echo $db_file
